### ISSUE TITLE
Move Email Settings onto Content Node

### ISSUE THREAD

**Issue by warrenbuckley** [warrenbuckley/CWS-Start#1]
Rather than the email settings be hard coded in the email helper class or even be in the smtp section of the web.config allow user to define directly on homenode as some kind of global setting for all emails perhaps?

**Comment by justinspradlin** [comment]
I think storing them as a new tab on the home page document type would be a good idea. That way if you ran multiple home page nodes with different domain names, you could have different settings for each "site". However, the helper would need to know which "site" it was running on to determine the smtp settings. That way the contact form from site1.com/contact would use the site1.com specific settings while site2.com/contact would use the site2.com node's settings.

**Comment by warrenbuckley** [comment]
This has been resolved with latest commit.

@justinspradlin this would be something you would have to extend yourself at this current time when you have the source code downloaded so you can tweak it to your own needs.

**Comment by justinspradlin** [comment]
That sounds great to me! Thanks!
