### ISSUE TITLE
Incorrect profile URL in Our project page

### ISSUE THREAD

**Issue by LottePitcher** [warrenbuckley/CWS-Start#16]
Hey Warren,

Just a quick one - on the Our Umbraco project page, the public url for member profiles is site.co.uk/profile/warrenbuckley.  It should be site.co.uk/user/warrenbuckley.  Confused me for a moment or two.  Really useful seeing custom routes in action (and seeing a good reason for doing one too!)

Lotte

**Comment by warrenbuckley** [comment]
@LottePitcher thanks for the heads up, just update the project page on our.umbraco now
