### ISSUE TITLE
Search box obscures page title when viewed on small devices screen size

### ISSUE THREAD

**Issue by mikeroyle** [warrenbuckley/CWS-Start#2]
When viewed at small devices screen size (>768px and <992px?) the search box drops below the main nav and obscures the main title of the page.
![image](https://f.cloud.github.com/assets/1257752/902234/5670b804-fb92-11e2-91a4-c669aa0600f6.png)

**Comment by warrenbuckley** [comment]
@mikeroyle can you please supply a screenshot for this to make my life easier.
This is vanilla Bootstrap out of the box so not sure what I will need to do to ensure it sorts itself out.

Cheers,
Warren :+1:

**Comment by mikeroyle** [comment]
Added to the original comment

**Comment by mikeroyle** [comment]
Don't know how I closed it - sorry!

**Comment by warrenbuckley** [comment]
@mikeroyle resolved with latest commit
