### ISSUE TITLE
Umbraco 6.1.6 compatability?

### ISSUE THREAD

**Issue by s6admin** [warrenbuckley/CWS-Start#25]
Hello friends,

After several tries installing 0.0.4 against a clean Umbraco 6.1.6 I'm having nothing but trouble getting any of the Membership functionality to work. Registration takes almost three minutes to complete (though the page never truly refreshes). Logging in never occurs either...the page simply processes the request indefinitely. We're running in a typical local dev environment using SQL 2008 RS and IIS7. Any insight would be greatly appreciated!

Thank you and keep up the amazing work!

**Comment by s6admin** [comment]
Determined that the login was hanging due to an unverified user email, though the page never displayed a message stating such.

Any suggestions as to why pages take so long to perform a postback on a local site setup?

**Comment by s6admin** [comment]
Managed to use the most recent master source and included the rebuilt DLL in our Umbraco demo project. Things run much more smoothly now. Could there be something amiss within the v0.0.4 package?

**Comment by warrenbuckley** [comment]
Hmm seems a little odd. I will close this for now, but feel free to re-open if you can provide more details/steps to reproduce
