### ISSUE TITLE
Registering - the profile url is assigned the NodeId

### ISSUE THREAD

**Issue by mikeroyle** [warrenbuckley/CWS-Start#3]
This is a bit confusing - maybe the user should be asked for the profile url at the point of registering if it needs to be a required field?

**Comment by warrenbuckley** [comment]
@mikeroyle OK I done this out of ease to begin with, rather than getting the user annoyed that their profile URL is not available. However see your point and will move it into the registration workflow instead

**Comment by warrenbuckley** [comment]
@mikeroyle this has been pushed up into the repo with a recent commit, but is not in a package just yet.
