### ISSUE TITLE
Install Error: No User exists with ID -1

### ISSUE THREAD

**Issue by KevinJump** [warrenbuckley/CWS-Start#9]
Umbraco 6.1.3 running SQLCE fresh install - suspect i've missed something

[ArgumentException: No User exists with ID -1]
   umbraco.BusinessLogic.User.setupUser(Int32 ID) +499
   umbraco.BusinessLogic.User..ctor(String Login) +75
   CWSStart.Web.CWSExtensions.RegisterStartupEvents.AddCustomMemberGroup() in c:\inetpub\wwwroot\Personal\CWS-Start\CWSStart.Web\CWSStart.Web\CWSExtensions\RegisterStartupEvents.cs:76
   CWSStart.Web.CWSExtensions.RegisterStartupEvents.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) in c:\inetpub\wwwroot\Personal\CWS-Start\CWSStart.Web\CWSStart.Web\CWSExtensions\RegisterStartupEvents.cs:37
   Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +37
   Umbraco.Core.CoreBootManager.<Complete>b__4(IApplicationEventHandler x) +19
   Umbraco.Core.EnumerableExtensions.ForEach(IEnumerable`1 items, Action`1 action) +141
   Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete) +119
   Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete) +26
   Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e) +157
   Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e) +9

**Comment by KevinJump** [comment]
i suspect this is because the default admin account on the install does not have a username of Admin 

the AddCustomMemberGroup() looks for the admin user 

var adminUser = new User(admin)

i think (i may be wrong) you can just create user 0 to do what you need. taken from the core... 

// Get current user, with a fallback
var currentUser = new User(0);

**Comment by warrenbuckley** [comment]
Thanks Kevin.
Just done a commit now to resolve this.

**Comment by s6admin** [comment]
This still occurs on a fresh 6.1.6 install when using CWS 0.0.4. Is there a workaround available?
